### ISSUE TITLE
Line Breaks not Recognized

### ISSUE THREAD

**Issue by DivertedCircle** [Pharylon/MithrilAlmanac#6]
Line breaks are not displayed properly when using timeline view, resulting in everything being merged into one giant paragraph.
![image](https://user-images.githubusercontent.com/26470570/72631597-b446fd80-3911-11ea-8cde-4beb3b13a2c3.png)
![image](https://user-images.githubusercontent.com/26470570/72631638-c7f26400-3911-11ea-8e6a-72fbd6aa867b.png)

**Comment by Pharylon** [comment]
Thanks for letting me know! I've fixed the error. 🙂
