### ISSUE TITLE
Moons don't allow 0 offset days

### ISSUE THREAD

**Issue by DivertedCircle** [Pharylon/MithrilAlmanac#8]
When trying to add moons into the Eberron calendar I discovered it's not possible to set up moons to have 0 offset days, so the very first day of the year has a full moon. Entering 0, hitting save, and reopening reveals that that moon offset has reset to the previous value.

**Comment by DivertedCircle** [comment]
Any chance of this getting fixed?

**Comment by Pharylon** [comment]
I've fixed this in the current build, thanks
